version: '3'

services:
  frontend:
    image: jurruh/chatbot-frontend
    restart: always
    networks:
      - traefik
      - chatbot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-frontend.rule=Host(`res.agendr.nl`)"
      - "traefik.http.routers.chatbot-frontend.entrypoints=websecure"
      - "traefik.http.routers.chatbot-frontend.priority=1"
      - "traefik.http.routers.chatbot-frontend.tls.certresolver=myresolver"
      - traefik.docker.network=traefik

  configurator:
    image: jurruh/chatbot-configurator
    restart: always
    networks:
      - traefik
      - chatbot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-configurator.rule=Host(`res.agendr.nl`)"
      - "traefik.http.routers.chatbot-configurator.rule=PathPrefix(`/configurator`)"
      - "traefik.http.routers.chatbot-configurator.entrypoints=websecure"
      - "traefik.http.routers.chatbot-configurator.priority=10"
      - "traefik.http.routers.chatbot-configurator.tls.certresolver=myresolver"
      - traefik.docker.network=traefik
      - "traefik.http.routers.chatbot-configurator.middlewares=configurator-strip"
      - "traefik.http.middlewares.configurator-strip.stripprefix.prefixes=/configurator"

  pytorch-chatbot:
    image: jurruh/pytorch-chatbot
    restart: always
    networks:
      - traefik
      - chatbot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-api.rule=Host(`res.agendr.nl`)"
      - "traefik.http.routers.chatbot-api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.chatbot-api.entrypoints=websecure"
      - "traefik.http.routers.chatbot-api.tls.certresolver=myresolver"
      - "traefik.http.routers.chatbot-api.middlewares=api-strip"
      - "traefik.http.routers.chatbot.priority=10"
      - traefik.docker.network=traefik
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.services.chatbot-api.loadbalancer.server.port=5000"


networks:
  traefik:
    external: true
  chatbot:      